#!/usr/bin/env python3

"""Build script for the HFST Python bindings.

All static project metadata lives in ``pyproject.toml`` (PEP 621). This file
only exists to build the C++ extension ``_libhfst``, which genuinely needs
imperative logic: a large source list, per-platform compiler/linker flags, and
two mutually exclusive link modes.

Two build modes
---------------

* **static** (default) — compile the whole of ``libhfst`` (plus the in-tree
  ``sfst`` back-end) directly into ``_libhfst`` and link the external back-ends
  (OpenFst ``-lfst``, foma ``-lfoma``), ICU and readline. This is what
  ``cibuildwheel`` uses to produce self-contained wheels; ``auditwheel`` /
  ``delocate`` then vendor the external shared libraries into the wheel.

* **shared** — set ``HFST_USE_SHARED_LIB=1`` to instead link against an
  already-installed ``libhfst`` (``-lhfst``) and compile only the SWIG wrapper.
  This is the path a distribution build (Debian ``python3-libhfst``) or the
  in-tree autotools build uses, reusing this same ``pyproject.toml``.

The flex/bison parser sources are generated by ``python/generate-parsers.sh``
(run automatically here if they are missing and ``bison``/``flex`` are on PATH).
The SWIG wrapper and ``libhfst.py`` shadow module are generated by setuptools'
SWIG integration from ``python/libhfst.i``.
"""

import os
import re
import subprocess
import sys
from glob import glob

from setuptools import Extension, setup
from setuptools.command.build_py import build_py as _build_py

HERE = os.path.abspath(os.path.dirname(__file__))


class build_py(_build_py):
    """Run build_ext first so SWIG has generated libhfst.py before it is copied.

    setuptools' default order runs build_py before build_ext, which would leave
    the SWIG-generated ``libhfst.py`` out of the wheel.
    """

    def run(self):
        self.run_command("build_ext")
        return super().run()


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _bool_env(name):
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes", "on")


def read_version():
    """Single source of truth for the version: configure.ac's HFST_VERSION."""
    configure_ac = os.path.join(HERE, "configure.ac")
    major = minor = ext = None
    with open(configure_ac, encoding="utf-8") as f:
        for line in f:
            m = re.match(r"\s*HFST_MAJOR=(\d+)", line)
            if m:
                major = m.group(1)
            m = re.match(r"\s*HFST_MINOR=(\d+)", line)
            if m:
                minor = m.group(1)
            m = re.match(r"\s*HFST_EXTENSION=(\d+)", line)
            if m:
                ext = m.group(1)
    if None in (major, minor, ext):
        # Fall back to the AC_INIT literal, e.g. AC_INIT([hfst],[3.17.1],...)
        with open(configure_ac, encoding="utf-8") as f:
            m = re.search(r"AC_INIT\(\[[^\]]*\],\s*\[(\d+\.\d+\.\d+)\]", f.read())
        if m:
            return m.group(1)
        raise RuntimeError("Could not determine version from configure.ac")
    return "{}.{}.{}".format(major, minor, ext)


def sources(pattern, exclude=()):
    """Glob ``pattern`` under the repo root, dropping ``exclude`` basenames.

    Returns paths relative to the repo root (== setup.py dir): setuptools
    rejects absolute paths in Extension.sources.
    """
    exclude = set(exclude)
    return [
        os.path.relpath(p, HERE)
        for p in sorted(glob(os.path.join(HERE, pattern)))
        if os.path.basename(p) not in exclude
    ]


PARSERS_DIR = os.path.join(HERE, "libhfst", "src", "parsers")


def ensure_generated_parsers():
    """Generate flex/bison parser sources if they are not already present."""
    sentinel = os.path.join(PARSERS_DIR, "xre_parse.cc")
    if os.path.exists(sentinel):
        return
    script = os.path.join(HERE, "python", "generate-parsers.sh")
    print("Generating flex/bison parser sources via", script)
    subprocess.check_call(["sh", script], cwd=PARSERS_DIR)


# ---------------------------------------------------------------------------
# extension configuration
# ---------------------------------------------------------------------------

platform = sys.platform
use_shared_lib = _bool_env("HFST_USE_SHARED_LIB")

swig_include_dir = os.path.join("libhfst", "src")
swig_opts = ["-c++", "-I" + swig_include_dir, "-Wall"]

include_dirs = [
    ".",
    os.path.join("libhfst", "src"),
    os.path.join("libhfst", "src", "parsers"),
    os.path.join("libhfst", "src", "implementations"),
    os.path.join("libhfst", "src", "implementations", "optimized-lookup"),
    os.path.join("back-ends"),
    os.path.join("back-ends", "sfst"),
]
# Allow CI (cibuildwheel before-all) to point at where it installed the
# from-source OpenFst / foma / ICU.
for extra in os.environ.get("HFST_EXTRA_INCLUDE_DIRS", "").split(os.pathsep):
    if extra:
        include_dirs.append(extra)
if os.path.isdir("/usr/local/include"):
    include_dirs.append("/usr/local/include")

library_dirs = []
for extra in os.environ.get("HFST_EXTRA_LIBRARY_DIRS", "").split(os.pathsep):
    if extra:
        library_dirs.append(extra)
if os.path.isdir("/usr/local/lib"):
    library_dirs.append("/usr/local/lib")

define_macros = [
    ("HAVE_OPENFST", None),
    ("HAVE_OPENFST_LOG", None),
    ("HAVE_FOMA", None),
    ("HAVE_SFST", None),
    ("USE_ICU_UNICODE", "1"),
]

libraries = ["fst", "foma", "icuuc", "icui18n", "icudata"]

extra_compile_args = []
extra_link_args = []

include_readline = platform.startswith("linux") or platform == "darwin"
if _bool_env("HFST_NO_READLINE"):
    include_readline = False
if include_readline:
    define_macros.append(("HAVE_READLINE", None))
    define_macros.append(("HAVE_GETLINE", None))
    libraries.append("readline")

# HFST uses C++20 library features (std::string::starts_with/ends_with,
# std::set::contains), so C++20 is the minimum standard.
if platform.startswith("linux") or platform == "darwin":
    extra_compile_args += ["-std=c++20", "-Wno-sign-compare", "-Wno-strict-prototypes"]
    libraries.append("dl")
if platform == "darwin":
    include_dirs.insert(0, os.path.join("python", "macos-compat"))
    define_macros.append(("HAVE_EXT_HASH_MAP", "1"))
    define_macros.append(("HAVE_EXT_HASH_SET", "1"))
    extra_compile_args += ["-stdlib=libc++"]
    extra_link_args += ["-stdlib=libc++"]
elif platform == "win32":
    extra_compile_args += ["/EHsc", "/std:c++20"]

# ----- source list -----

if use_shared_lib:
    # Link against an already-built libhfst; only wrap it.
    ext_sources = [os.path.join("python", "libhfst.i")]
    libraries = ["hfst"]
    lib_dir = os.environ.get("HFST_LIBRARY_DIR")
    if lib_dir:
        library_dirs.append(lib_dir)
        extra_link_args.append("-Wl,-rpath," + os.path.abspath(lib_dir))
    define_macros = [("USE_ICU_UNICODE", "1")]
else:
    ensure_generated_parsers()
    ext_sources = [os.path.join("python", "libhfst.i")]
    ext_sources += sources("libhfst/src/*.cc", exclude=["HfstXeroxRulesTest.cc"])
    ext_sources += sources(
        "libhfst/src/implementations/*.cc",
        exclude=[
            "XfsmTransducer.cc",
            "MyTransducerLibraryTransducer.cc",
            "HfstTransitionGraph.cc",
        ],
    )
    ext_sources += sources("libhfst/src/implementations/optimized-lookup/*.cc")
    ext_sources += sources("libhfst/src/implementations/compose_intersect/*.cc")
    # Committed + flex/bison-generated parser sources (all are compiled).
    ext_sources += sources("libhfst/src/parsers/*.cc")
    ext_sources += sources("libhfst/src/parsers/*/*.cc")
    # In-tree SFST back-end.
    ext_sources += sources("back-ends/sfst/*.cc")

libhfst_module = Extension(
    "_libhfst",
    language="c++",
    sources=ext_sources,
    swig_opts=swig_opts,
    include_dirs=include_dirs,
    library_dirs=library_dirs,
    libraries=libraries,
    define_macros=define_macros,
    extra_compile_args=extra_compile_args,
    extra_link_args=extra_link_args,
)

setup(
    version=read_version(),
    cmdclass={"build_py": build_py},
    ext_modules=[libhfst_module],
    py_modules=["libhfst"],
    packages=[
        "hfst",
        "hfst.exceptions",
        "hfst.sfst_rules",
        "hfst.xerox_rules",
    ],
    package_dir={"": "python"},
)
